### ISSUE TITLE
npm rum dev 在mac下一直报错

### ISSUE THREAD

**Issue by bairdweng** [mint-ui/mint-ui-starter#3]
<img width="948" alt="2016-12-19 4 06 15" src="https://cloud.githubusercontent.com/assets/8598304/21305151/cd9898d0-c604-11e6-92df-10bc741182bc.png">

**Comment by mingmingwon** [comment]
`Error: getaddrinfo ENOTFOUND localhost`
**解决办法**：在 host 文件中添加 `127.0.0.1 localhost`

**Comment by mingmingwon** [comment]
在 host 文件中添加 `**127.0.0.1 localhost**` 即可 @bairdweng

**Comment by mingmingwon** [comment]
在 host 文件中添加 **`127.0.0.1 localhost`** 即可 @bairdweng

**Comment by bairdweng** [comment]
谢谢！已经搞定了，是端口被占用了。
