### ISSUE TITLE
一clone下来就跑就报错。

### ISSUE THREAD

**Issue by callmesoul** [mint-ui/mint-ui-starter#4]
`
(node:4856) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

`

不影响运行，但是打包时也报这个错。打包少了很多文件。求尽快处理下。

**Comment by QingWei-Li** [comment]
麻烦学会看提示信息

**Comment by callmesoul** [comment]
看了，英文看不懂，哭死

**Comment by QingWei-Li** [comment]
这个是  `loader-utils` 的提示，只是警告用户未来版本会更改 API。`vue-loader` 里用到了这玩意，等 vue-loader 更新就好了

**Comment by callmesoul** [comment]
但是没法打包啊？有其他解决办法 ？

**Comment by QingWei-Li** [comment]
贴报错信息

**Comment by callmesoul** [comment]
`10% building modules 5/5 modules 0 active(node:1756) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.`

打包后没css，没index.html好像少很多文件

**Comment by QingWei-Li** [comment]
这个 starter 只是个示范，推荐还是用官方的模板

**Comment by callmesoul** [comment]
好吧，哭死了，我都用这个写完了，就差打包
