### ISSUE TITLE
移动设备不能自适应

### ISSUE THREAD

**Issue by c446984928** [mint-ui/mint-ui-starter#6]
该项目创建的页面，pc访问正常，移动设备访问字体非常小，感觉像是完全没有适配，是否因为没有加入example项目中的 @reset-global mobile;？

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/mint-ui/mint-ui-starter/commit/3e6cb978409ae59fbc681fa98e768e99ad30ca37
